### ISSUE TITLE
Support for Events API

### ISSUE THREAD

**Issue by AlainODea** [okta/okta-sdk-java#102]
We use the [Events API](https://developer.okta.com/docs/api/resources/events.html) in production to:

 1. Allow customers to see logs specific to their IdP for SSO self-troubleshooting (used with a target ID obtained from the [Identity Providers API](/okta/okta-sdk-java/issues/101))

**Comment by AlainODea** [comment]
@bdemers this is the logging API we are using in production. We can't migrate to the new style of SDK until this is in it.

**Comment by bdemers** [comment]
Hey @AlainODea!

We are not likely to implement the Events API in the new SDKs as this endpoint is being replaced by the Logs API. It will be a while before this effect any apps in production (See the noticed on https://developer.okta.com/docs/api/resources/events):

However, the workaround looks something like this
```java
client.getDataStore().getResource("/api/v1/events", EventsList.class).stream()
                .forEach(event -> {
                    System.out.println(event);
                });
```
and your resource classes:

```java
public class Event extends AbstractResource {

        public Event(InternalDataStore dataStore) {
            super(dataStore);
        }

        public Event(InternalDataStore dataStore, Map<String, Object> properties) {
            super(dataStore, properties);
        }

        @Override
        public Map<String, Property> getPropertyDescriptors() {
            return createPropertyDescriptorMap();
        }
    }
```

```java
    public class EventsList extends AbstractCollectionResource<Event> {

        private static final ArrayProperty<Event> ITEMS = new ArrayProperty<>("items", Event.class);

        public EventsList(InternalDataStore dataStore) {
            super(dataStore);
        }

        public EventsList(InternalDataStore dataStore, Map<String, Object> properties) {
            super(dataStore, properties);
        }

        public EventsList(InternalDataStore dataStore, Map<String, Object> properties, Map<String, Object> queryParams) {
            super(dataStore, properties, queryParams);
        }

        @Override
        public Map<String, Property> getPropertyDescriptors() {
            return createPropertyDescriptorMap(ITEMS);
        }

        @Override
        protected Class<Event> getItemType() {
            return Event.class;
        }
    }
```

Since, many of the current endpoints were generated, we didn't notice there is some code that could be be moved up into a parent class (`getItemType`, `getPropertyDescriptors` of the CollectionResource) opened: #183

One downside is this requires a compile dependency on the `okta-sdk-impl` module (not the end of the world, but worth pointing out)

And in my example the `Event` Object must be treated as a map, this was done to keep the example brief, but you could implement typed getters for the values you expected.

I'm going to close this issue, but your feedback is welcome on this suggestion!

**Comment by AlainODea** [comment]
Thank you very much for the detailed workaround, @bdemers. I’ll give that a shot!
