### ISSUE TITLE
Authentication support in SDK

### ISSUE THREAD

**Issue by RvPr** [okta/okta-sdk-java#106]
Hi. I'm migrating over from Stormpath, and am looking for the Okta equivalent of the following [AuthenticateUser API](https://github.com/stormpath/stormpath-sdk-java/blob/97dee12e734bf5fbca02145b35271f8a39888aca/api/src/main/java/com/stormpath/sdk/application/Application.java#L501). 

As far as I can tell, the closest equivalent is [the primary-authentication-with-public-application API](https://developer.okta.com/docs/api/resources/authn.html#primary-authentication-with-public-application).

Can you please clarify if I'm on the right track, and if the above functionality will be supported in the SDK during the next month?

**Comment by bdemers** [comment]
@RvPr The AuthN API would be the way to go.  We are planning on adding this functionality, but it will likely not happen within the month.  Please contact support@stormpath.com with any questions about migration, we can help suggest alternatives.

**Comment by me717** [comment]
Has this ever been implemented? I am looking at upgrading from version 0.0.4 of the Okta sdk, but this is a feature we would need.

**Comment by howardbright** [comment]
Fwiw, I'm using the current latest version of the SDK (0.0.6) and the [AuthenticateUser API](https://github.com/stormpath/stormpath-sdk-java/blob/97dee12e734bf5fbca02145b35271f8a39888aca/api/src/main/java/com/stormpath/sdk/application/Application.java#L501) is not implemented in it. I've defaulted to using [Primary Authentication with Trusted Application](https://developer.okta.com/docs/api/resources/authn.html#primary-authentication-with-trusted-application) for the authentication part, and using the SDK for User and Group CRUD.

**Comment by joellundell** [comment]
Hi!

We're trying to reduce the number of calls we're making to okta cause we sometimes get rate-limited. We wanted to use the built in caching mechanism but it lost some of it's value for us because the authentication using access-token and refresh-token is not built in to the SDK. Is this something you plan on implementing or maybe there's another approach/best practice to limit the number of calls we make for authenticating users using access tokens?

Sorry for hi-jacking the thread but it's related to the authentication and maybe it can help other people too.

Thank you,
Joel

**Comment by bdemers** [comment]
We are keeping the SDK and the authentication/authorization projects decoupled when possible.

Take a look at these projects:
* okta/okta-jwt-verifier-java - generic Java ID and access token handling
* okta/okta-spring-security - Okta client side access token handling 

Though in the near future we will also allow access to the SDK from integrations like Spring, in order to do things like go from the current logged in Principal to an Okta SDK 'User' class (like we did with Stormpath's integrations)

**Comment by me717** [comment]
@bdemers Does this mean the AuthN api will not be supported in the Okta SDK? Neither repo you linked seems to handle that.

**Comment by bdemers** [comment]
@me717 we will be working on that.  Not sure which repo it will fit into yet.
A lot of AuthN use cases can be handled by OAuth/OIDC flows (transparent to the developer/user). There are a few things that cannot be like the Sessions API.

Which AuthN API calls are you using today?  (this will help us prioritize the order we work on them)

**Comment by bdemers** [comment]
AuthN support will likely NOT go in this repo.  If we support it will likely be a separate project.  I'd highly recommend looking at OAuth/OIDC flows as a replacement.
