### ISSUE TITLE
Allow creation of users in group

### ISSUE THREAD

**Issue by johnoliver** [okta/okta-sdk-java#112]
There appears to be no way to create a user in a specific group, i.e use: https://developer.okta.com/docs/api/resources/users.html#create-user-in-group 

This makes it impossible use an api token that only has permissions to administer users in a specific group, since you must first provision a user with no group, which it is not allowed to do.

**Comment by bdemers** [comment]
This isn't supported using the SDK API directly because we needed to simplify some of the models for the SDK.  That said, this could be done with a compile dependency on `okta-sdk-impl`, (which we do not recommend).

You could extend the `DefaultUser` and add an array property for `groupIds`:
```java
private static final ArrayProperty<Factor> GROUP_IDS = new ArrayProperty<>("groupIds", String.class);
```
(above snippet mostly from memory, so YMMV)


We should be able to hide all of these complexities in the `UserBuilder` in the future.
Thanks for the report!
