### ISSUE TITLE
Okta List factor discrepancy between API and Admin console

### ISSUE THREAD

**Issue by nsrirameig** [okta/okta-sdk-java#1548]
### Describe the bug?

I am currently using Okta sdk for java to retrieve user factors , this is more of question than a bug. Consider user has call, email and SMS, if we disable  call factor at the policy level .  List factors  API only returns sms and email but  call factor is not being returned , but admin console does return all 3.  Is there a flag that could be passed to listFactors API call  , to ensure consistency btw api and admin console.

### What is expected to happen?

Consider user has call, email and SMS, if we disable  call factor at the policy level .  List factors  API only returns sms and email but  call factor is not being returned , but admin console does return all 3.  API {url}/api/v1/users/{userId}/factors

### What is the actual behavior?

Admin console using the same api returns all 3.

### Reproduction Steps?

Execution of API

### Additional Information?

None

### Java Version

OpenJDK Runtime Environment Temurin-17.0.11+9 (build 17.0.11+9)
OpenJDK 64-Bit Server VM Temurin-17.0.11+9 (build 17.0.11+9, mixed mode)

### SDK Version

18.0.0

### OS version

N/A

**Comment by arvindkrishnakumar-okta** [comment]
@nsrirameig Thanks for posting!

Have you tried the request using POSTMAN or curl and is there discrepancy? 

Note that this repo is reserved for issues/feature requests only, if you have a general question or use case question please post in https://devforum.okta.com/

**Comment by nsrirameig** [comment]
Thanks for the prompt response . I  did try the request through postman, thats where the discrepancy  was . I apologize for posting the question here, , will ask the question in dev forum in future. Admin  console for that user show all the factors , sms, call and email  but postman shows only  sms and email.

**Comment by arvindkrishnakumar-okta** [comment]
Thanks, since the SDK’s response is consistent with POSTMAN, this is not a SDK issue.On Aug 28, 2024, at 11:26 AM, nsrirameig ***@***.***> wrote:﻿

This message originated outside your organization.
  

Thanks for the prompt response . I  did try the request through postman, thats where the discrepancy  was . I apologize for posting the question here, , will ask the question in dev forum in future. Admin  console for that user show all the factors , sms, call and email  but postman shows only  sms and email.

**Comment by nsrirameig** [comment]
Thanks , closing it out.
