### ISSUE TITLE
Case sensitivity with environment variables in DefaultClientBuilder

### ISSUE THREAD

**Issue by kgeckhart** [okta/okta-sdk-java#256]
I am attempting to use the DEFAULT_CLIENT_TESTING_DISABLE_HTTPS_CHECK_PROPERTY_NAME override for testing in a conditional manner. Setting the value via environment variable was the most ideal and looked like it supported was by the [DefaultClientBuilder](https://github.com/okta/okta-sdk-java/blob/master/impl/src/main/java/com/okta/sdk/impl/client/DefaultClientBuilder.java). However this particular configuration setting is okta.testing.disableHttpsCheck which does not have a custom override in [DefaultEnvVarNameConverter](https://github.com/okta/okta-sdk-java/blob/master/impl/src/main/java/com/okta/sdk/impl/config/DefaultEnvVarNameConverter.java) to account for the change in case with disableHttpsCheck. 

DisableHttpsCheck is not the only setting which currently has this casing problem and is missing an override. I have a fix in mind which would change the Map used by DefaultClientBuilder to be case insensitive. I would be willing to make the change if this strategy makes sense.

**Comment by bdemers** [comment]
Thanks for the report @kgeckhart !

I'd like to keep the case sensitivity, so other configuration sources (like Spring env for example would work).  Either way though this should be easy enough to get into the next release.

Possibly... instead of hardcoding the list of special values, we could convert the dotted properties to the ENV form and create a reverse lookup map 🤔 

In the short term (i'm guessing you already figured this out) but you can just set the equivalent system property
