### ISSUE TITLE
Check Rate Limit using Okta Java API Client?

### ISSUE THREAD

**Issue by calebpowell** [okta/okta-sdk-java#319]
I want to ensure my code respects the Okta API rate limit. The REST API returns the header ‘X-Rate-Limit-Remaining’ in the response for each API call to inform the client of how many future requests they can make in the current window. Is it possible to access this header via the Java SDK?

(apologies if this is the wrong forum to post a question like this, but there is an issue label named 'question').

**Comment by bdemers** [comment]
I see, assuming you expect to be under the rate limits, for your scheduled task, you could either keep the defaults or set the maxAttempts=-1, maxElapsed=5 minutes (or some other window you are comfortable with)

For the initial burst, this depends on how much data you have. I'd probably recommend the same retry settings, but suggest you add an artificial delay (if you have a lot of data)

Since this is a scheduled task, you can also trigger `n` number of groups and user per minute. I'm guessing some fraction of your rate limits (to give room to any other applications that might be accessing the API).

Does that help?

**Comment by calebpowell** [comment]
That helps! Thanks for taking the time to reply to this!

**Comment by bdemers** [comment]
Any time @calebpowell !
