### ISSUE TITLE
Support of Push Factor Challenge's Poll for Verify Transaction Completion

### ISSUE THREAD

**Issue by herospYL** [okta/okta-sdk-java#321]
I'm currently developing with this Java SDK on two factor issues. Currently I could use the SDK to issue a PUSH factor challenge, however, I cannot find the "Poll for verify transaction completion" method anywhere. 

If it's not supported yet, is there any way I can use the client to send a HTTP request and get a raw response?

If none of those are supported, can you tell me how can I verify a PUSH factor's challenge?

Thank you

**Comment by bdemers** [comment]
This is supported in our Authentication SDK: https://github.com/okta/okta-auth-java

You can also call arbitrary Okta endpoints using: https://github.com/okta/okta-sdk-java#call-other-api-endpoints (this works with both SDKs)

**Comment by kevintian** [comment]
@bdemers Sorry to necro a dead thread, but I wanted to clarify on your answer here - it looks like Authentication SDK requires a state token in order to poll for the push factor, so since the Factors API endpoint to send a Push challenge does not return a state token (since it's not part of the authentication state machine), there's no way to use the polling functionality in the Authentication SDK with a push challenge sent via the Factors API. 

Then that means the only solution here would be to manually call the polling endpoint inside of the Factors API `(/api/v1/users/{{userId}}/factors/{{factorId}}/transactions/{{transactionId}})` using the generic syntax then, right?

**Comment by bdemers** [comment]
@kevintian  I'm not sure I'm fully following the question, but I'll take a shot at answering.

The Auth SDK is only for calls under `/api/v1/authn`, usually with the goal of authenticating a user.

Requests under `/api/v1/users/{userId}}factors` would fall under this project.

Which method are you using to start the challenge?  And taking a step back, what are you trying to accomplish (maybe we can offer a suggestion)?

**Comment by kevintian** [comment]
@bdemers Sure, happy to clarify, and thanks for your help!

So I am trying to implement MFA in two places - I want to allow users to be able to enroll in/configure their MFA factors after they've already authenticated, and I was going to use the Factors API to achieve this functionality.

In addition, I also want a user to be able to enroll in MFA factors during the authentication process if they do not already have a factor configured, aka when they are put into the MFA_ENROLL state. I was going to use the Auth SDK for this functionality.

I'd love to hear your thoughts on this configuration - this is what I interpreted as the "intended" use case for the two APIs but if I could simplify my work and only have to implement one of the two APIs to handle both scenarios, that'd be even better :)

My above question relates to my first use case, when a user is already logged in and authenticated. I wanted to send a push challenge to the user as a "test" and would be starting the challenge using the Factors API. However, I was a bit confused on the recommended way to poll for the successful completion of this challenge - am I correct in assuming that for this specific use case, the only way to poll for a result would be using the `(/api/v1/users/{{userId}}/factors/{{factorId}}/transactions/{{transactionId}})` endpoint?

**Comment by bdemers** [comment]
Ahh, OK :) there are a few questions in there so I'll try to answer them all, and just yell if I missed something!

Easy ones first:
Polling: This usually depends on the factor.  For example, a push notification requires polling because the "factor" is submitted from another device (e.g. your phone, watch, etc).  For TOTP factors (Google authenticator) you don't need to poll, you just submit the code, and check the response.

Your overall strategy could work, use the `/authn` API when the user logs in and the `/api/v1/users/*` API after that. 

However, we usually steer people away from using the `/authn` when possible (its great when you need to integrate with a legacy system, or when you are migrating users into Okta). But... Using an OAuth flow is usually a better option. Less code to write, Okta handles it all for you, user passwords never touch your system, you don't need to update a custom UI when you want to add features, like adding MFA registration.

You can customize the login page (and have Okta host it on a custom domain like id.example.com).

Does that help?

**Comment by kevintian** [comment]
Thank you, this definitely helps a lot! I really appreciate you taking your time to clear this up for me.

Just to be sure, when you say OAuth flow, do you mean redirecting to Okta and using Okta's hosted login page?

**Comment by bdemers** [comment]
Correct!
