### ISSUE TITLE
Security Vulnerability in sub dependency jar

### ISSUE THREAD

**Issue by amit70** [okta/okta-sdk-java#448]
We are using this plugin part of spring boot project and performed a Veracode Security scan on it, it resulted in a security vulnerability. Please find the attached screenshot.

![Screen Shot 2020-08-24 at 8 40 56 AM](https://user-images.githubusercontent.com/2734831/91065612-8fbcad80-e5e5-11ea-8c23-5419990a7266.png)

Did a quick research and found the sub dependency **bcprov-jdk15on-1.64.jar** is being used within okta-sdk-impl.

Any suggestions/help would be appreciated.

**Comment by bdemers** [comment]
Which vulnerability is reported? This might be a false positive as `1.66` is the current version.

One of the easiest ways to deal with vulnerabilities in your transitive dependencies is to add them to your "Dependency Management" section in your Maven Pom file (or Gradle equivalent).

That said, we also want to make sure we are using the latest version, so I've pushed a PR: #449 to update to the latest.

**NOTE:** This version shows up with an issue with your scan, so we would need to see the details to confirm it is a false positive. (false positives are NOT uncommon with these types of scans, but we would still like to be sure 😉)

**Comment by amit70** [comment]
Thanks @bdemers  for you response. My apologies, I should have shared the vulnerability details in my last comment. See below.

<img width="948" alt="Screen Shot 2020-08-24 at 9 12 22 AM" src="https://user-images.githubusercontent.com/2734831/91069246-0360b980-e5ea-11ea-8a88-3fcf90aec3df.png">

**Comment by bdemers** [comment]
This looks like a usage-specific issue with the library. It's covered in more detail here:
https://bugzilla.redhat.com/show_bug.cgi?id=1563749

Basically it seems that this issue was "fixed" in 1.47, but then reintroduced as a legacy option in 1.49 to retain backward compatibility.

There is nothing a consumer of this library can do other than NOT use the legacy feature, .i.e a keystore with a format of `BKS-V1`. Well, almost nothing, I would suggest raising the issue with the Bouncy Castle team.

**NOTE:** The Okta SDK only uses Bouncy Castle directly to parse PEM files.

**Comment by bdemers** [comment]
I'm going to close the issue, but feel free to keep asking questions, and I can re-open it if needed.

**Comment by amit70** [comment]
The fact that Okta sdk does not utilize legacy feature from the library makes things a bit simpler. Thanks for pointing it out and appreciate your help here.

**Comment by bdemers** [comment]
Any time! these things are difficult to track down!
