### ISSUE TITLE
Enable access to response headers ( i.e. rate limit headers )

### ISSUE THREAD

**Issue by adipetre** [okta/okta-sdk-java#578]
### I'm submitting a
  - [ ] bug report
  - [x] feature request

### Background info

We have a use case in which we need to know when we're approaching our organisation's rate limits for user logins / user creation, etc. This information is returned in the headers X-Rate-Limit-Limit, X-Rate-Limit-Remaining, X-Rate-Limit-Reset for most api calls.
Using either okta-sdk-java or okta-auth-java sdk, all responses contain only the resource body returned by Okta; all headers are stripped - for instance the AuthenticationResponse object after logging in a user, or the com.okta.sdk.resource.user.User object after creating an user.

### Expected behavior

All resources should provide access to the response's headers.
Making the API calls directly, all headers are present in the response, something the SDK doesn't provide access to.

### What went wrong?

There is no way to access the response's headers.
Looking into the code - in com/okta/sdk/impl/ds/DefaultDataStore.java, the function
```
private <T extends Resource, R extends Resource> R save(String href,
                                                            final T resource,
                                                            final T parentResource,
                                                            HttpHeaders requestHeaders,
                                                            final Class<? extends R> returnType,
                                                            final QueryString qs,
                                                            final boolean create)
```
makes the request to Okta at line 331, but then complete ignores the contents of the response headers:
```
            Response response = execute(request);
            Map<String, Object> responseBody = getBody(response);
            if (Collections.isEmpty(responseBody)) {
                // Fix for https://github.com/stormpath/stormpath-sdk-java/issues/218
                // Okta response with 200 for deactivate requests (i.e. /api/v1/apps/<id>/lifecycle/deactivate)
                if (response.getHttpStatus() == 202
                        || response.getHttpStatus() == 200
                        || response.getHttpStatus() == 204) {
                    //202 means that the request has been accepted for processing, but the processing has not been completed. Therefore we do not have a response setBody.
                    responseBody = java.util.Collections.emptyMap();
                } else {
                    throw new IllegalStateException("Unable to obtain resource data from the API server.");
                }
            }

            ResourceAction responseAction = getPostAction(req, response);

            return new DefaultResourceDataResult(responseAction, uri1, returnType, responseBody);
```

### Steps to reproduce

Create or log in a user using the SDKs

### SDK Version
4.0.0

**Comment by sergiishamrai-okta** [comment]
Thanks for the request @adipetre 
I'm going to create an internal task for our team. Please, follow this issue for updates.

**Comment by sergiishamrai-okta** [comment]
Internal ref: OKTA-390428

**Comment by mattdrees** [comment]
We'd be interested in some way of tracking these headers, as well.
As-is, I don't think the okta java sdk allows us to follow the best practice described here:
https://developer.okta.com/docs/reference/rl-best-practices/#check-your-rate-limits-with-okta-s-rate-limit-headers

**Comment by bdemers** [comment]
@mattdrees

Out of the box, the SDK has configured retries based these headers.

If you need more control over this, you can configure retry options:
https://github.com/okta/okta-sdk-java#connection-retry--rate-limiting

The TL;DR is if you have a batch process, you can increase the timeout/retry count. If you are building an end user-facing app you want to keep them shorter.

If an exception is thrown and you want to inspect those headers you should be able to call something like: `exception.getError().getHeaders()`

But if the exception is rate limit related, the SDK's configure retry configuration has already been exhausted.

**Comment by mattdrees** [comment]
Hi Brian, thanks for the note. The auto-retry feature is pretty neat; I don't think I've seen that in any sdks I've worked with before. Good docs, too. (Kudos!)

But I don't think that's what adipetre was asking for, and it's not what I'm needing either.
The retry feature is reactive. We're both looking for a way to be proactive. 

In my case, I've been burned by the org rate limit several times now. I really want to know when things are getting bad before I get burned another time. The okta system log doesn't give you this granularity of data. Near as I can tell the only way to get it is to log the rate limit headers on a constant basis, and capture/alert on that. (In my case, I want to use a datadog log-based-metric, and set up an alert when we're consistently over say 70% of our org rate limit.)

I'll admit I haven't dug into which http library the sdk uses and figured out if it has some way to log certain headers. Probably if it does, it's going to be more verbose than I'm looking for. But the sdk docs don't specify which http library or logging library is used, so I'd be relying on impl details. So I think it'd be really useful to have some sanctioned approach for capturing the rate limit headers, whether that's via a 'getHeaders' method like this issue is asking for or whether that's a config option to just log the rate limits.

**Comment by bdemers** [comment]
Logging the rate limit header could be a quick win 🤔

Returning them as part of the response would be much more difficult. (The actual response could be pulled from cache, and some objects are returned as a list and individual so there is no _natural_ place to put a “getHeaders()” method on a non-error response ). 

Let’s back up for a bit, other than alerting what action would your app take once you start nearing a rate-limit cap? (Maybe there is something else we could do 🤔,  like fire an event? Mostly thinking out loud)

(replying on mobile forgive my formatting)

**Comment by mattdrees** [comment]
> Returning them as part of the response would be much more difficult

True, and honesty in my case I don't really want to be responsible for collecting and logging headers. I'd rather the sdk just log them. I can't speak on behalf of the original poster here, but I think there's a good chance logging would work well for them too.


Other than alerting, I'm not sure what an app would reasonably do with rate limit info. Possibly it could start queueing work for later, instead of executing it right now. 
Perhaps it could activate a warning banner telling users that we're experiencing high traffic, and ask for their patience in case problems pop up. 
But neither of those are very strong arguments for programmatic access to headers, IMO.

**Comment by bdemers** [comment]
@mattdrees very helpful, thank you for getting back to us!

@adipetre (if you are still watching this issue) any thoughts on this?

**Comment by mattdrees** [comment]
> Near as I can tell the only way to get it is to log the rate limit headers on a constant basis, and capture/alert on that. 

I think this isn't strictly true, anymore; Okta released a [rate limit dashboard](https://developer.okta.com/docs/reference/rl-dashboard/) recently that might be pretty helpful.

**Comment by VitaliiTytarenko-okta** [comment]
@adipetre @mattdrees 
Please let us know if this is still relevant for you or [Rate limit dashboard](https://developer.okta.com/docs/reference/rl-dashboard/) covers all your needs.

**Comment by VitaliiTytarenko-okta** [comment]
Feel free to reopen this if you have any questions.

**Comment by dziedrius** [comment]
As others mentioned, getting exception/seeing in dashboard is too late already.
We have background jobs, syncing information from time to time and they don't have same priority as user initiated requests, hence we would prefer background job sleep a bit until rate limit is recovered than kill rate completely so that users would start getting errors.
okta terraform provider seems to implement this nicely by having max requests setting, where you set percent of rate limit used before throttling kicks in.
