### ISSUE TITLE
First class deleteUser Client method.

### ISSUE THREAD

**Issue by er1c** [okta/okta-sdk-java#733]
### Describe the feature request?

I would like a first class api call to make this request using the SDK (e.g. client.deleteUser(..., ...)

### New or Affected Resource(s)

https://developer.okta.com/okta-sdk-java/development/apidocs/com/okta/sdk/client/Client.html

### Provide a documentation link

https://developer.okta.com/docs/reference/api/users/#delete-user

**Comment by arvindkrishnakumar-okta** [comment]
@er1c Thanks for posting!

Due to the way we presently generate the models from Open API Spec v2, we generate the `deleteUser` operation on the `User` model object itself and not on the `Client` object. 

You should be able to invoke the `delete` API on `User` object - see https://github.com/okta/okta-sdk-java/blob/master/integration-tests/src/test/groovy/com/okta/sdk/tests/it/UsersIT.groovy#L557

We have plans to migrate to Open API v3 soon and with this all the API operations will be invokable via the `Client` reference (no operations would live inside models like it does presently).

**Comment by arvindkrishnakumar-okta** [comment]
Update: With the latest 10.0.0 release, we've fixed this.

Ref: https://github.com/okta/okta-sdk-java/blob/master/examples/quickstart/src/main/java/quickstart/Quickstart.java#L118
